# sub-finder/.github/workflows/backend_docker.yml
name: backend_docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image using docker-compose
        run: docker-compose up -d --build
      - name: Check running containers
        run: docker ps -a
      - name: Run test suite
        run: docker-compose exec -T backend sh -c "pytest . && flake8"
